version: '3.9'

services:
  django-web:
    build: ./backend
    container_name: django
    env_file: .env
    volumes:
      - ./backend/static:/app/staticfiles
    networks:
      - billing-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - MIKROTIK_URL=${MIKROTIK_URL}
      - MIKROTIK_USER=${MIKROTIK_USER}
      - MIKROTIK_PASS=${MIKROTIK_PASS}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0,192.168.68.108}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-http://localhost,http://127.0.0.1,http://0.0.0.0,http://192.168.68.108,http://192.168.68.108:80}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost,http://127.0.0.1,http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://127.0.0.1:80,http://192.168.68.108,http://192.168.68.108:80}

  nextjs:
    build: ./frontend
    container_name: nextjs
    networks:
      - billing-network
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-/api/v1}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/static:ro
    depends_on:
      - django-web
      - nextjs
    networks:
      - billing-network

networks:
  billing-network:
    driver: bridge
